### ISSUE TITLE
Making use of the Wiki tab on GitHub

### ISSUE THREAD

**Issue by rikutakei** [swcarpentry-ja/i18n#27]
@TomKellyGenetics The README seems to contain a lot of detailed descriptions about how the git/po integration works and the logic behind it, and some stuff on setting up the (what I assume) the original i18n repo.

I feel like this is not necessarily what people need to know when they first arrive at the repo, but rather how to contribute to the translation of the material.

Would it be a good idea to utilise the "Wiki" tab on GitHub?

We could place the more technical aspects that take up a lot of space in the README to the Wiki as a separate topic/page, and guide people to the Wiki if they require more details and/or want to help out in the git/po integration side of things.

**Comment by TomKellyGenetics** [comment]
It’s already been suggested to use the Wiki Tab for glossary terms. I think it’s a great idea for anything specific to Japanese. Anything we want merged with i18n should stay in the README. Since ours is more detailed than the original, I think this is one of the reasons they want to merge (even if the lessons are incomplete).

https://github.com/swcarpentry-i18n/i18n/pull/10

So I think guidelines specific to Japanese language should be in the Wiki. Instructions for managing the PO files should be markdown files tracked in the repo, although these could be linked from the README, rather than cluttering it.

**Comment by rikutakei** [comment]
Yep, agreed with creating a separate README for managing PO files.

May be worth while to add all technical details (not just Japanese translation specfic stuff) to the Wiki in the future - obviously this won't be a priority, so probably disregard it for now

**Comment by TomKellyGenetics** [comment]
Yes, I’ve discussed this with @joelnitta and we think the README is too long and needs splitting up as well. I’ll have a think about how to go about this. @dpshelio is also going to work on documentation for the i18n repo so let’s keep an eye on what we can use from there.
