### ISSUE TITLE
Can't compile with po4gitbook

### ISSUE THREAD

**Issue by joelnitta** [swcarpentry-ja/i18n#38]
I can't get `po4gitbook/compile.sh` to work. This is what I've tried:

1. Fork https://github.com/swcarpentry-ja/i18n to my github account (https://github.com/joelnitta/i18n).
2. Clone my fork locally.
3. Run `git submodule init` followed by `git submodule update` to populate submodules.
4. From the project root, run `po4gitbook/compile.sh`. This is what I get:

```
Compiling *.es.po ...
Compiling /Users/joelnitta/tmp/i18n/po/git-novice.es.po ...
Traceback (most recent call last):
  File "po4gitbook/tools/poc.py", line 313, in <module>
    c.run()
  File "po4gitbook/tools/poc.py", line 305, in run
    self.verify()
  File "po4gitbook/tools/poc.py", line 125, in verify
    raise MissingCreditException()
__main__.MissingCreditException: Credit is missing on the header description, should be like this "# FULL NAME <EMAIL@ADDRESS>, YEAR1, YEAR2."
```

I've also tried running `po4gitbook/update.sh` first, then `compile.sh`. `update.sh` works, but I get the same error with `compile.sh`.

Has there been a change in `po4gitbook` that means we need to change the formatting of the header section of the PO files? 

I thought perhaps it's because 2019 needs to get added to the credit line of the header. I tried adding 2019 to the credit lines, of all `PO` files, e.g.:

```
# Japanese translation of the Software Carpentry Git Lesson
# Copyright (C) 2018 Software Carpentry Foundation; Japanese Translation Team
# This file is distributed under the same license as the gitbook package.
# Riku Takei <riku.takei@otago.ac.nz>, 2018.
```

to 

```
# Japanese translation of the Software Carpentry Git Lesson
# Copyright (C) 2018 Software Carpentry Foundation; Japanese Translation Team
# This file is distributed under the same license as the gitbook package.
# Riku Takei <riku.takei@otago.ac.nz>, 2018, 2019.
```

I then tried `update.sh` followed by `compile.sh`, but get the same error.

**Comment by rikutakei** [comment]
Hey, I got the same error going through what you did.

The bug is coming from testing the latest year on the header line with the current year.

There's a bug in `po4gitbook/tools/poc.py` on line 110: 

```python
years = poline[:-1].split('>')[1].split(', ')[1]
```

This splits the last bit of the credit (i.e. the year(s)) into a list of **three** items: empty string, first year, and second year (if present), and so the code above only takes the second item, which is the "old" year (i.e. 2018).

Since "2018" is not "2019", so it throws an error about the credential being wrong.

The fix is to just change the index in the above code so it takes the last item, no matter how many years present:

```python
years = poline[:-1].split('>')[1].split(', ')[-1]
```

Give the above code a go after you have edited the years in all the `po/*.po` files.

Cheers

**Comment by joelnitta** [comment]
Thanks that fixed it! I submitted a PR: https://github.com/swcarpentry-i18n/po4gitbook/pull/2, should be able to close this once that is merged.

**Comment by dpshelio** [comment]
Thanks @rikutakei and @joelnitta for the fix! It's merged already.

**Comment by joelnitta** [comment]
Great! Closing this then.
