### ISSUE TITLE
Inconsistency in translating title, teaching, exercises, questions, objectives, and keypoints

### ISSUE THREAD

**Issue by atusy** [swcarpentry-ja/i18n#41]
Any ideas to fix inconsistently translated terms in different lessons?

| Original | #39 | #37  | #35 |
|-|-|-|-|
| title | タイトル | title | タイトル |
| teaching | 講義 | teaching | 講義 |
| exercises | 練習 | exercises | 練習 |
| questions | 質問 | 質問 | 質問 |
| objectives | 目的 | 目的 | 目標 |
| keypoints | 要点 | まとめ | キーポイント |

Links to relevant lines.

#39 https://github.com/swcarpentry-ja/i18n/pull/39/files#diff-627559538775bc873d27f74c80ae4d17R13386

#37 https://github.com/swcarpentry-ja/i18n/pull/37/files#diff-6e60cd31417a84efd5e7e33396f557c8R738

#35 https://github.com/swcarpentry-ja/i18n/pull/35/files#diff-627559538775bc873d27f74c80ae4d17R12386

**Comment by TomKellyGenetics** [comment]
This is an excellent point. I think it is possible to add these to the wiki so we agree on consistent translations for common terms.

**Comment by atusy** [comment]
I will discuss this topic on translating "marathon" and make feedback.

**Comment by rikutakei** [comment]
Wow, didn't realise I skipped "title", "exercise", and "teaching" out... :grimacing: 

At least for the "title", I left it as is since I thought that it was some sort of a header for the compiler to recognise and format it accordingly, because you don't see it in the final [webpage](https://swcarpentry.github.io/git-novice/01-basics/index.html).
I'm not quite sure why I haven't/didn't translate the others - will keep an eye out for the future translation.

@atusy If you come up with good term(s) for those words, let us know. Alternatively, we might be able to make a poll on slack to see what everyone thinks the consensus should be.

**Comment by TomKellyGenetics** [comment]
I'd err towards katakana terms (as long as they'll be understood) unless we have a good reason not to. That might just be my native language showing though 😄 

Maybe not so important for headings but for programming terminology, if they can learn to understand names of concepts it might help.

**Comment by TomKellyGenetics** [comment]
@rkkmk has suggested these on Slack:

objectives: 目標
keypoints: 要点

This seems to resolve it if #37 was a misunderstanding to leave the English terms. So it's just a matter to editing these for consistency (please add to the Wiki pages as well).

Perhaps we should update this as well? It's metadata for translating the website headings (across lessons). I translated it for the demo at Tokyo.R (so it's probably got mistakes).

https://github.com/swcarpentry-ja/i18n/blob/ja/lang.md

**Comment by TomKellyGenetics** [comment]
This is now addressed with changes to the theme: https://github.com/carpentries-i18n/carp-theme/pull/9

See here for why we don't change the headings in the PO file.
https://carpentries-i18n-handbook.readthedocs.io/en/latest/guide/translator/01_format.html#yaml-front-matter-block
https://github.com/swcarpentry-ja/i18n/blob/ja/docs/quickstart.md#headings-in-lesson-preamble
