### ISSUE TITLE
Changelog out of date

### ISSUE THREAD

**Issue by TomKellyGenetics** [swcarpentry-ja/i18n#51]
The following file is still mentioned in the README but it is very out of date.

> We have a change log to track progress and goals.

Since we now have many translations underway, perhaps it is better to remove this and direct people to open issues and PRs.

**Comment by joelnitta** [comment]
Agreed. On a related note, this was proposed during the last meeting by @rikutakei :

(riku) we are thinking of splitting episodes into sections and submit issues for each sections. Workflow idea: 
announce which lesson\episode to be translated
submit all issues on Github, so everyone knows which parts/sections are going to be translated
each person assign themselves to an issue for translation
commit and pull request when finished

I like this idea and think we should implement it. I think it will basically replace the changelog. "R for Reproducible Scientific Analysis" (AKA R-novice-gapminder) is already far enough along that it doesn't need this treatment, but I think we should choose the next lesson(s) to try this out. Maybe git-novice and shell-novice since they've both just gotten underway?

**Comment by TomKellyGenetics** [comment]
Yes, I liked this idea as well. Turns out we may need to check through the existing readmes to make sure they're consistent. I'd like to try splitting the shell/git lessons into smaller sections and see if we can more progress that way.
