### ISSUE TITLE
Proposal to change to moderator system to manage translations

### ISSUE THREAD

**Issue by TomKellyGenetics** [swcarpentry-ja/i18n#56]
There seems to be a lull in activity as PRs are not merged. At the moment, there is clear expectations to review each lesson before merging but it is unclear when it is ready to merge. I would prefer this to be a community decision based on reviews but someone needs to make a the final decision.

To encourage more reviews, I think that anyone can give a review. They do not have to be a _reviewer_ for that lesson. I think we should nominate a _moderator_ or two for each lesson. Who will make the final decision to merge PRs. If reviews get complicated or there is a disagreement, it would be helpful to have someone familiar with our system nominated to resolve it.

I propose to nominate moderators and update the guides for translators and admins accordingly.

**Comment by rikutakei** [comment]
I think there was a lull partly because there were too many lessons (and material) to be reviewed at once in a single PR (i.e. #42). For the other ones, I think it won't be too much of a problem in the future as they are split into a single lesson - it was just that one particular PR that caused much more hassle than we (or at least I) expected. 

I think we already have asked people to send PRs in a per-lesson fashion, but in the future, we should decline PRs unless they are in a single lesson chunk.

As for moderators - yes and no.
Yes, because of the situation we had in #42 - someone needs to make a call in the end.
No, because hopefully, in the future, there won't be any PRs like #42 (fingers crossed🤞).

Agree that anyone should be able to review, but only if they are able to give a high quality review. No point in recruiting reviewers if moderators (or other reviewers) keep having to correct them.

I feel like having moderators would be a good idea once we have enough reviewers, so perhaps hold on to this idea for now, and implement it when we have more reviewers.

**Comment by TomKellyGenetics** [comment]
I think we largely agree. I'd prefer if moderators weren't often needed. Having multiple reviewers seems to be working well. If we can split up lessons into smaller sections, then I'd expect we won't have as many issues.

I'd encourage "peer-reviews" (translators to give each other feedback), rather than leaving it up to one person. Yeah, I'm thinking about what would work in the long-term.

For splitting up the R lessons, see #55 for details on following up from PR #42.

**Comment by TomKellyGenetics** [comment]
Closing as mergify and GH Actions automates this if 2 reviews are approved.
